package com.bonc.codeCenter.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SB_MDM_MDM_InquiryEnterpriseInfoSrv", targetNamespace = "http://mss.unicom.com/SB_MDM_MDM_InquiryEnterpriseInfoSrv")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SBMDMMDMInquiryEnterpriseInfoSrv {

	/**
	 * 
	 * @param payload
	 * @return returns
	 *         com.bonc.codeCenter.ws.service.SBMDMMDMInquiryEnterpriseInfoSrvResponse
	 */
	@WebMethod(action = "process")
	@WebResult(name = "SB_MDM_MDM_InquiryEnterpriseInfoSrvResponse", targetNamespace = "http://mss.unicom.com/SB_MDM_MDM_InquiryEnterpriseInfoSrv", partName = "payload")
	public SBMDMMDMInquiryEnterpriseInfoSrvResponse process(
			@WebParam(name = "SB_MDM_MDM_InquiryEnterpriseInfoSrvRequest", targetNamespace = "http://mss.unicom.com/SB_MDM_MDM_InquiryEnterpriseInfoSrv", partName = "payload")
			SBMDMMDMInquiryEnterpriseInfoSrvRequest payload);

}
